[package]
name = "{{ crate_name }}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["{{ lib_type }}", "lib"]
name = "{{ namespace }}"

[dependencies]
uniffi = "0.28"

{% if !macro_only %}
[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }
{%- endif %}
