name: Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "12 16 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo Outdated
        run: cargo outdated -i cargo_metadata --exit-code 1
      - name: Cargo Audit
        run: cargo audit -D warnings
