name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: olix0r/cargo-action-fmt/setup@v2
      - name: Check
        run: cargo check -q --message-format=json | cargo-action-fmt
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test --verbose
      - name: Publish (Dry Run)
        run: cargo publish --dry-run --allow-dirty
