name: Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: olix0r/cargo-action-fmt/setup@v2
    - name: Clippy
      run: set -o pipefail && cargo clippy -q --message-format=json -- -D warnings | cargo-action-fmt
